SET IDENTITY_INSERT [dbo].[Scores] ON
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (1, N'dum da dum', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (2, N'not dum da dum', 3, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3, N'ole', 4, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (4, N'smelly ole', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (5, N'dub man', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (6, N'slubby slo', 4, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (7, N'toledo joe', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (8, N'high chapparal', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (9, N'nike', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (10, N'crudel', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (1010, N'etyr', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (2010, N'boogie', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3010, N'charleen', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3011, N'sandii', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3012, N'lauryn', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3013, N'jolien', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3014, N'nanci', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3015, N'carol', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3016, N'tracii', 3, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3017, N'lacii', 3, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3018, N'lena', 4, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3019, N'erotaz', 3, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3020, N'tjabo', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3021, N'lori', 3, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3022, N'jane', 4, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3023, N'loryn', 5, NULL)
INSERT INTO [dbo].[Scores] ([Id], [Player], [Points], [QuizId]) VALUES (3024, N'kati', 5, NULL)
SET IDENTITY_INSERT [dbo].[Scores] OFF
